// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAN6-zo-L4engdgKtKW3214LJoeg0SM9tQ',
    appId: '1:918624153266:web:ab3fdc943c2f74884263ab',
    messagingSenderId: '918624153266',
    projectId: 'my-wh-project-2025',
    authDomain: 'my-wh-project-2025.firebaseapp.com',
    storageBucket: 'my-wh-project-2025.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBW0fX-a2p0l5_CP1xjbHkQOAjVLZJjB0k',
    appId: '1:918624153266:android:1c805f9afe4a23ae4263ab',
    messagingSenderId: '918624153266',
    projectId: 'my-wh-project-2025',
    storageBucket: 'my-wh-project-2025.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCv0nXUTDo_cqadaZps569Gn8Oy9T0qg3M',
    appId: '1:918624153266:ios:64c288f65f2308bb4263ab',
    messagingSenderId: '918624153266',
    projectId: 'my-wh-project-2025',
    storageBucket: 'my-wh-project-2025.firebasestorage.app',
    iosBundleId: 'com.example.workHoursTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCv0nXUTDo_cqadaZps569Gn8Oy9T0qg3M',
    appId: '1:918624153266:ios:64c288f65f2308bb4263ab',
    messagingSenderId: '918624153266',
    projectId: 'my-wh-project-2025',
    storageBucket: 'my-wh-project-2025.firebasestorage.app',
    iosBundleId: 'com.example.workHoursTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAN6-zo-L4engdgKtKW3214LJoeg0SM9tQ',
    appId: '1:918624153266:web:02d91904c8ff03234263ab',
    messagingSenderId: '918624153266',
    projectId: 'my-wh-project-2025',
    authDomain: 'my-wh-project-2025.firebaseapp.com',
    storageBucket: 'my-wh-project-2025.firebasestorage.app',
  );
}
